In [68]:
import pandas as pd

In [69]:
scms = pd.read_csv("./arquivos/SCMs.csv")
scms['presenca'] = True
scms

           SCM  presenca
0     2242-212      True
1     2242-221      True
2     2242-234      True
3     2242-211      True
4     3215-331      True
...        ...       ...
5725  3241-322      True
5726  3241-354      True
5727  3241-361      True
5728  3241-324      True
5729  3234-224      True

[5730 rows x 2 columns]

In [124]:
mdss = pd.read_csv("./arquivos/MDSs.csv", encoding = "utf-16")
mdss = mdss.drop(columns=['FullPath'])
mdss = mdss.sort_values(by=['SCM', 'Version'])
mdss

           SCM                      Name Version
3517  2122-211  MDS_2122-211_1000_v2.laz      v2
3518  2122-212  MDS_2122-212_1000_v2.laz      v2
3519  2122-213  MDS_2122-213_1000_v2.laz      v2
3520  2122-214  MDS_2122-214_1000_v2.laz      v2
3521  2122-221  MDS_2122-221_1000_v2.laz      v2
...        ...                       ...     ...
1342  4445-313  MDS_4445-313_1000_v0.laz      v0
1343  4445-341  MDS_4445-341_1000_v0.laz      v0
1344  4445-342  MDS_4445-342_1000_v0.laz      v0
1345  4445-343  MDS_4445-343_1000_v0.laz      v0
1346  4445-344  MDS_4445-344_1000_v0.laz      v0

[5654 rows x 3 columns]

In [140]:
# localizando os duplicados
mdss_duplicados = mdss[mdss.duplicated(['SCM'], keep=False)]
mdss_duplicados = mdss_duplicados[mdss_duplicados.duplicated(['SCM'], keep='last')]

#removendo os duplicados
mdss = mdss.drop(mdss_duplicados.index)

# Salvando para CSV
mdss.to_csv(path_or_buf='./arquivos/MDSs_unicos.csv')
mdss

           SCM                      Name Version
3517  2122-211  MDS_2122-211_1000_v2.laz      v2
3518  2122-212  MDS_2122-212_1000_v2.laz      v2
3519  2122-213  MDS_2122-213_1000_v2.laz      v2
3520  2122-214  MDS_2122-214_1000_v2.laz      v2
3521  2122-221  MDS_2122-221_1000_v2.laz      v2
...        ...                       ...     ...
1342  4445-313  MDS_4445-313_1000_v0.laz      v0
1343  4445-341  MDS_4445-341_1000_v0.laz      v0
1344  4445-342  MDS_4445-342_1000_v0.laz      v0
1345  4445-343  MDS_4445-343_1000_v0.laz      v0
1346  4445-344  MDS_4445-344_1000_v0.laz      v0

[5544 rows x 3 columns]

In [141]:
mdts = pd.read_csv("./arquivos/MDTs.csv", encoding = "utf-16")
mdts = mdts.drop(columns=['FullPath'])
mdts

           SCM                      Name Version
0     2322-222  MDT_2322-222_1000_v1.laz      v1
1     2322-224  MDT_2322-224_1000_v1.laz      v1
2     2322-231  MDT_2322-231_1000_v1.laz      v1
3     2322-232  MDT_2322-232_1000_v1.laz      v1
4     2322-233  MDT_2322-233_1000_v1.laz      v1
...        ...                       ...     ...
5467  3326-412  MDT_3326-412_1000_v4.laz      v4
5468  3326-413  MDT_3326-413_1000_v4.laz      v4
5469  3326-414  MDT_3326-414_1000_v4.laz      v4
5470  3326-441  MDT_3326-441_1000_v4.laz      v4
5471  3326-442  MDT_3326-442_1000_v4.laz      v4

[5472 rows x 3 columns]

In [142]:
# Identificando os duplicados
mdts_duplicados = mdts[mdts.duplicated(['SCM'], keep=False)]
mdts_duplicados = mdts_duplicados[mdts_duplicados.duplicated(['SCM'], keep='last')]

# REmovendo linhas duplicadas
mdts = mdts.drop(mdts_duplicados.index)

# Salvando CSV
mdts.to_csv(path_or_buf='./arquivos/MDTs_unicos.csv')
mdts

           SCM                      Name Version
0     2322-222  MDT_2322-222_1000_v1.laz      v1
1     2322-224  MDT_2322-224_1000_v1.laz      v1
2     2322-231  MDT_2322-231_1000_v1.laz      v1
3     2322-232  MDT_2322-232_1000_v1.laz      v1
4     2322-233  MDT_2322-233_1000_v1.laz      v1
...        ...                       ...     ...
5467  3326-412  MDT_3326-412_1000_v4.laz      v4
5468  3326-413  MDT_3326-413_1000_v4.laz      v4
5469  3326-414  MDT_3326-414_1000_v4.laz      v4
5470  3326-441  MDT_3326-441_1000_v4.laz      v4
5471  3326-442  MDT_3326-442_1000_v4.laz      v4

[5362 rows x 3 columns]

## Identificando os SCMs que não tem MDS

In [145]:
scms_mdss = pd.merge(left=scms,right=mdss, how='left', left_on='SCM', right_on='SCM')
scms_sem_mds = scms_mdss[scms_mdss.Name.isnull()]
pd.set_option('display.max_rows', 20)
display(scms_sem_mds.SCM)
scms_sem_mds.SCM.to_csv(path_or_buf='./arquivos/SCMs_sem_MDS.csv')

265     3225-333
273     3225-331
275     3225-321
276     3225-334
278     3225-324
          ...
5721    3241-332
5722    3241-364
5724    3241-334
5725    3241-322
5727    3241-361
Name: SCM, Length: 199, dtype: object

C:\Users\D877341\AppData\Local\Continuum\miniconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  """

## Identificando os MDSs que não tem MDT

In [144]:
mdss_mdt = pd.merge(left=mdss,right=mdts, how='left', left_on='SCM', right_on='SCM')
mdss_sem_mdt = mdss_mdt[mdss_mdt.Name_y.isnull()]
pd.set_option('display.max_rows', 200)
display(mdss_sem_mdt.Name_x)
mdss_sem_mdt.Name_x.to_csv(path_or_buf='./arquivos/MDSs_sem_MDT.csv')

0       MDS_2122-211_1000_v2.laz
2       MDS_2122-213_1000_v2.laz
7       MDS_2122-224_1000_v2.laz
10      MDS_2122-233_1000_v2.laz
11      MDS_2122-251_1000_v2.laz
12      MDS_2222-131_1000_v0.laz
14      MDS_2222-162_1000_v1.laz
19      MDS_2222-213_1000_v0.laz
29      MDS_2222-241_1000_v1.laz
77      MDS_2224-114_1000_v1.laz
78      MDS_2224-121_1000_v1.laz
120     MDS_2224-312_1000_v1.laz
121     MDS_2224-321_1000_v1.laz
122     MDS_2224-322_1000_v1.laz
127     MDS_2224-413_1000_v1.laz
137     MDS_2224-442_1000_v1.laz
140     MDS_2224-453_1000_v1.laz
170     MDS_2226-413_1000_v0.laz
180     MDS_2226-441_1000_v0.laz
182     MDS_2226-443_1000_v0.laz
192     MDS_2242-113_1000_v0.laz
193     MDS_2242-114_1000_v0.laz
196     MDS_2242-143_1000_v0.laz
227     MDS_2242-311_1000_v0.laz
323     MDS_2244-311_1000_v2.laz
327     MDS_2244-323_1000_v2.laz
348     MDS_2244-443_1000_v2.laz
358     MDS_2246-211_1000_v2.laz
360     MDS_2246-214_1000_v2.laz
363     MDS_2246-223_1000_v2.laz
370     MDS_2246-254_1000_v2.laz
376     MDS_2246-423_1000_v2.laz
382     MDS_2246-442_1000_v2.laz
383     MDS_2246-444_1000_v2.laz
392     MDS_2322-221_1000_v1.laz
394     MDS_2322-223_1000_v1.laz
416     MDS_2324-222_1000_v1.laz
417     MDS_2324-224_1000_v1.laz
422     MDS_2324-244_1000_v1.laz
424     MDS_2324-253_1000_v1.laz
430     MDS_2324-333_1000_v2.laz
432     MDS_2324-343_1000_v2.laz
434     MDS_2324-352_1000_v2.laz
507     MDS_2326-254_1000_v1.laz
523     MDS_2326-424_1000_v1.laz
527     MDS_2326-451_1000_v1.laz
535     MDS_2342-134_1000_v1.laz
536     MDS_2342-154_1000_v1.laz
541     MDS_2342-211_1000_v1.laz
572     MDS_2342-353_1000_v2.laz
602     MDS_2344-121_1000_v2.laz
610     MDS_2344-142_1000_v2.laz
611     MDS_2344-144_1000_v2.laz
644     MDS_2344-312_1000_v2.laz
645     MDS_2344-314_1000_v2.laz
734     MDS_2346-351_1000_v0.laz
736     MDS_2346-354_1000_v0.laz
771     MDS_2441-451_1000_v2.laz
780     MDS_2442-223_1000_v2.laz
782     MDS_2442-233_1000_v2.laz
783     MDS_2442-234_1000_v2.laz
784     MDS_2442-242_1000_v2.laz
785     MDS_2442-243_1000_v2.laz
803     MDS_2442-331_1000_v2.laz
843     MDS_2443-222_1000_v2.laz
849     MDS_2443-252_1000_v2.laz
852     MDS_2443-263_1000_v1.laz
854     MDS_2443-432_1000_v1.laz
951     MDS_2446-111_1000_v1.laz
962     MDS_2446-142_1000_v1.laz
964     MDS_2446-152_1000_v1.laz
965     MDS_2446-153_1000_v1.laz
966     MDS_2446-162_1000_v1.laz
981     MDS_2446-243_1000_v1.laz
992     MDS_2446-414_1000_v1.laz
1003    MDS_2446-453_1000_v1.laz
1004    MDS_2446-454_1000_v1.laz
1011    MDS_3112-221_1000_v2.laz
1012    MDS_3112-222_1000_v2.laz
1139    MDS_3212-224_1000_v1.laz
1388    MDS_3214-464_1000_v1.laz
1529    MDS_3216-264_1000_v1.laz
1579    MDS_3225-312_1000_v1.laz
1582    MDS_3225-323_1000_v1.laz
1587    MDS_3225-351_1000_v1.laz
1588    MDS_3225-353_1000_v1.laz
2036    MDS_3235-344_1000_v2.laz
2039    MDS_3235-353_1000_v2.laz
2063    MDS_3235-453_1000_v2.laz
2064    MDS_3235-461_1000_v2.laz
2125    MDS_3236-341_1000_v2.laz
2128    MDS_3236-352_1000_v2.laz
2129    MDS_3236-361_1000_v2.laz
2131    MDS_3236-364_1000_v2.laz
2142    MDS_3236-434_1000_v2.laz
2158    MDS_3241-121_1000_v1.laz
2159    MDS_3241-123_1000_v1.laz
2164    MDS_3241-151_1000_v1.laz
2165    MDS_3241-153_1000_v1.laz
2178    MDS_3241-352_1000_v1.laz
2205    MDS_3243-331_1000_v2.laz
2214    MDS_3243-363_1000_v2.laz
2225    MDS_3245-143_1000_v2.laz
2227    MDS_3245-152_1000_v2.laz
3265    MDS_3325-422_1000_v4.laz
3267    MDS_3325-424_1000_v4.laz
3270    MDS_3325-434_1000_v4.laz
3331    MDS_3326-323_1000_v4.laz
3337    MDS_3326-361_1000_v4.laz
3355    MDS_3326-453_1000_v1.laz
3729    MDS_3334-432_1000_v1.laz
3912    MDS_3336-412_1000_v0.laz
3915    MDS_3336-421_1000_v0.laz
3920    MDS_3336-453_1000_v0.laz
3955    MDS_3341-251_1000_v1.laz
3956    MDS_3341-253_1000_v1.laz
3972    MDS_3341-344_1000_v1.laz
3975    MDS_3341-353_1000_v1.laz
3976    MDS_3341-361_1000_v1.laz
3979    MDS_3341-413_1000_v1.laz
3980    MDS_3341-421_1000_v1.laz
3981    MDS_3342-222_1000_v1.laz
3984    MDS_3343-111_1000_v1.laz
4000    MDS_3426-313_1000_v1.laz
4006    MDS_3426-331_1000_v1.laz
4018    MDS_3426-362_1000_v1.laz
4020    MDS_3426-364_1000_v1.laz
4055    MDS_3431-411_1000_v2.laz
4062    MDS_3431-451_1000_v2.laz
4064    MDS_3431-454_1000_v2.laz
4065    MDS_3432-343_1000_v2.laz
4068    MDS_3432-354_1000_v2.laz
4069    MDS_3432-364_1000_v2.laz
4102    MDS_3433-231_1000_v2.laz
4103    MDS_3433-232_1000_v2.laz
4189    MDS_3434-213_1000_v2.laz
4190    MDS_3434-214_1000_v2.laz
4191    MDS_3434-223_1000_v2.laz
4192    MDS_3434-224_1000_v2.laz
4193    MDS_3434-232_1000_v2.laz
4448    MDS_3441-133_1000_v1.laz
4449    MDS_3441-134_1000_v1.laz
4450    MDS_3441-154_1000_v1.laz
4455    MDS_3441-211_1000_v1.laz
4479    MDS_3441-321_1000_v1.laz
4487    MDS_3441-342_1000_v1.laz
4489    MDS_3441-344_1000_v1.laz
4530    MDS_3442-131_1000_v1.laz
4641    MDS_3444-111_1000_v1.laz
4642    MDS_3444-113_1000_v1.laz
4742    MDS_3446-251_1000_v2.laz
4964    MDS_4312-433_1000_v0.laz
4970    MDS_4312-452_1000_v0.laz
5106    MDS_4314-252_1000_v1.laz
5146    MDS_4314-434_1000_v1.laz
5329    MDS_4316-421_1000_v1.laz
5330    MDS_4316-422_1000_v1.laz
5341    MDS_4321-121_1000_v0.laz
5342    MDS_4321-123_1000_v0.laz
5346    MDS_4321-151_1000_v0.laz
5347    MDS_4325-113_1000_v1.laz
5348    MDS_4331-111_1000_v1.laz
5350    MDS_4331-121_1000_v1.laz
5358    MDS_4331-164_1000_v1.laz
5373    MDS_4331-243_1000_v1.laz
5383    MDS_4331-431_1000_v1.laz
5405    MDS_4332-162_1000_v1.laz
5407    MDS_4332-211_1000_v1.laz
5408    MDS_4332-213_1000_v1.laz
5409    MDS_4332-321_1000_v1.laz
5410    MDS_4332-322_1000_v1.laz
5417    MDS_4435-254_1000_v2.laz
5418    MDS_4435-263_1000_v0.laz
5419    MDS_4435-264_1000_v0.laz
5468    MDS_4436-133_1000_v0.laz
5469    MDS_4436-134_1000_v0.laz
5470    MDS_4436-141_1000_v0.laz
5482    MDS_4436-241_1000_v0.laz
5484    MDS_4436-252_1000_v0.laz
5485    MDS_4436-253_1000_v0.laz
5488    MDS_4436-262_1000_v0.laz
5541    MDS_4445-342_1000_v0.laz
Name: Name_x, dtype: object

C:\Users\D877341\AppData\Local\Continuum\miniconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  """